### ISSUE TITLE
Лаба 2

### ISSUE THREAD

**Issue by irinamatveeva** [testmapper-official/SqlDatabaseSSAU#1]
Орфографические ошибки в комментариях.
Задание 6 - лучше выводить не все данные, а только "объекты" (если просят только "объекты"). Это касается и следующих заданий тоже.
Задание 7 - рекомендуется OR использовать IN(....)
Задание 11 - нужно комментарий получше, не совсем ясно, что вы сделали.
Задание 13 - почему именно столько людей? не много ли?

**Comment by testmapper-official** [comment]
6: Надеюсь, исправил. Но вообще, когда пишут объект, не совсем понятно, что имеет ввиду человек. В том смысле, что прежде всего объект подразумевается, в первую очередь, как один блок данных в таблице (в табличном виде - строка). Но даже так, в задании не сказано, что нужно вывести наименование объекта (а выдумывать свое, что не сказано в задании, когда-нибудь аукнется).
7: Учтено.
11: Переделал сам запрос, так как некорректная связка ключей была. Комментарий также. Проверьте, пожалуйста.
13: Как говорилось в комментарии, "Выбирает последних зарегистрировавшихся людей клуба за все время". В задании не сказано, сколько я должен человек взять, поэтому я взял всех начиная с последнего вступившего по самого первого. Если не так, уточните, что в задании имелось ввиду, пожалуйста.

**Comment by testmapper-official** [comment]
И соответственно, 1я лаба исправлена (убраны лишние файлы). Тоже проверьте.

**Comment by lasbio** [comment]
6: Цель задания - научить делать только выборку нужных параметров, т.к. использование "SELECT * ..." слишком затратно.  Сейчас задание выполнено правильно, но Ваш комментарий не корректен. Пояснение:   В задание термин "объект" задан по описанию предметной области ( т.е. "объект" == "facility") и вряд ли допускает двойное толкование.  Строка таблицы  == "объект" - это частный случай.  Строка может содержать и множество объектов - например, поля, в которых содержаться объекты (BLOB, JSON и т.д.), каждое из них содержит свой объект (причем разного типа).  Кроме того, в SQL БД данные нормализованы, т.е. "физический объект предметной области" распределен по многим таблицам.  Пример - таблица адресов содержит только часть адреса (улица, дом квартира), а город, страна - в других таблицах, на которую из таблицы адресов идут ссылки.  
11:  У Вас идет многократное повторение объектов, т.к. Вы попытались объединить покупки, членов и объектов. Причем не факт, что среди отобранных будут все члены клуба, ибо (а) могут быть члены, которые еще ничего не покупали (только зарегистрировались), и (б) есть еще и гости клуба, которых Вы не исключили.  
Цель задания - показать, что в одном запросе могут объединяться разнородные "объекты предметной области".  Подсказка: использовать UNION.
13: Читайте внимательно задание. Термин "последних зарегистрировавшихся" имеет ЕДИНСТВЕННОЕ толкование == "члены клуба с наиболее поздней датой регистрации" . Таких может быть один или несколько или все, если все зарегистрировались одновременно.
Обращаю Ваше внимание, что любое программное решение начинается с тщательного изучения и понимания/ осознания "предметной области". Для учебного примера "предметная область" ==  "формулировка задания".

**Comment by testmapper-official** [comment]
![изображение_2023-10-23_141223288](https://github.com/testmapper-official/SqlDatabaseSSAU/assets/67954166/bb639695-7d8c-484f-b248-4df48d6db2cf)
![изображение_2023-10-23_141241986](https://github.com/testmapper-official/SqlDatabaseSSAU/assets/67954166/a6ca3ac0-a3a3-46ec-9034-d35c989119f4)

Единственное, что я нашел в документе про обозначение слова "объекты" это то, что их обозначают как facilities (то есть, таблица).

Кстати, в замечании не было указано, скорее всего, пропустили, но я также исправил 8-й файл, так как там требовалось ИМЯ ОБЪЕКТА и обозначение его стоимости (ДЕШЕВЫЙ или ДОРОГОЙ), а не весь объект в том числе.

Исправлено, проверьте, пожалуйста.

**Comment by lasbio** [comment]
Все задания формируются по предметной области и в ее терминах: термин объект, на английском == facility ,  а объекты, на английском == facilities.  Все названия в базе данных конечно же выбираются со смыслом, т.е. с привязкой к предметной области. Это касается как названия самих таблиц, так и названия полей таблицы.  Именно поэтому в заданиях есть совпадения английских терминов  предметной области и названий ряда объектов БД.  Если брать конкретно по таблице facilities, то она содержит список всех объектов (в терминах предметной области) вместе с их характеристиками, т.е. таблица facilities == [ facility row], facility row =  { facility (== объект, название объекта), параметр объекта 1, параметр объекта 2, ....}.  
Задания 8 не было в замечаниях, значит, оно было уже зачтено (т.е. Ваши исправления приняты) ранее.
Задание 14 правильно.
