### ISSUE TITLE
root

### ISSUE THREAD

**Issue by lasbio** [testmapper-official/SqlDatabaseSSAU#2]
Какую роль в Вашем проекте играет файл main.py?
Если у Вас в проекте в процессе разработки появляются какие-либо файлы, которые не будут использоваться, то они должны быть либо удалены (через git), либо внесены в gitignore. Иначе, при скачивании вашего проекта кем-то из команды или Вами, эти файлы будут клонироваться.

**Comment by testmapper-official** [comment]
Удалено.
